name: CI - Nextflow test
# This workflow is triggered on pushes and PRs to the repository.
on:
  push:
    branches: [ dev-ci ]
  pull_request:
    branches: [ dev-ci ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nxf_ver: ['21.04.1']
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install Nextflow
        run: |
          export NXF_VER=${{ matrix.nxf_ver }}
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Basic workflow tests
        run: |
          nextflow run ${GITHUB_WORKSPACE} --config test.config